modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ftblibrary"
mandatory = true
versionRange = "[${ftb_library_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ftbteams"
mandatory = true
versionRange = "[${ftb_teams_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ftbquests"
mandatory = true
versionRange = "[${ftb_quests_version},)"
ordering = "AFTER"
side = "BOTH"
